% =============================================================================
% server/intelligence/prolog/cs.rules.pl
%
% Static inference rules loaded after the per-note facts generated by
% graph.engine.ts → prolog.engine.ts. Facts are ground (no variables);
% everything in here is derived.
%
% Fact functors produced upstream (see graph.engine.ts):
%   paper(NoteId).
%   method(NoteId, ConceptId).
%   dataset(NoteId, ConceptId).
%   accuracy(NoteId, Value).
%   solves(NoteId, TaskId).
%   is_a(ConceptId, AncestorId).        — one fact per consecutive ancestor pair
%   part_of(ConceptId, ConceptId).
%   uses(ConceptId, ConceptId).
%   related_to(ConceptId, ConceptId).   — concept-to-concept only
%   mentions(NoteId, ConceptId).        — paper-to-concept "extra entity" edge
%                                          (was emitted as related_to/2 — renamed
%                                          to avoid colliding with the
%                                          concept-to-concept related_to/2 above)
%   trained_on(NoteId, ConceptId).
%   concept_solves(ConceptId, ConceptId). — ontology-declared "solves" relation
%                                          between two concepts (was plain
%                                          solves/2 — renamed to avoid colliding
%                                          with the paper-level solves(NoteId,
%                                          TaskId) fact above, same functor/arity)
%
% Every rule here is read by tau-prolog at session load time, after the
% per-note facts have already been consulted. Rule order matters only for
% the recursive belongs_to/2 — base case must precede the recursive case.
% =============================================================================

% ── Hierarchy traversal ───────────────────────────────────────────────────────
% belongs_to(Concept, Domain) succeeds if Concept is Domain itself, or any
% ancestor in its is_a OR part_of chain is Domain. graph.engine.ts emits both
% relation types for ontology-derived edges (e.g. cnn part_of computer_vision,
% cnn is_a deep_learning) — domain membership can travel through either, so
% both base cases and both recursive cases are needed.

belongs_to(Concept, Domain) :-
  is_a(Concept, Domain).
belongs_to(Concept, Domain) :-
  part_of(Concept, Domain).
belongs_to(Concept, Domain) :-
  is_a(Concept, Mid),
  belongs_to(Mid, Domain).
belongs_to(Concept, Domain) :-
  part_of(Concept, Mid),
  belongs_to(Mid, Domain).

% ── Domain classification ─────────────────────────────────────────────────────
% A paper is classified into a domain through whatever method it uses.
% These feed directly into key_fact/3 below for quiz generation and into
% chat.service.ts's questionToGoal() for "what field is this paper in?".

computer_vision_paper(Paper) :-
  method(Paper, Method),
  belongs_to(Method, computer_vision).

nlp_paper(Paper) :-
  method(Paper, Method),
  belongs_to(Method, nlp).

ml_paper(Paper) :-
  method(Paper, Method),
  belongs_to(Method, ml).

systems_paper(Paper) :-
  method(Paper, Method),
  belongs_to(Method, systems).

% ── Quality inference ─────────────────────────────────────────────────────────
% Accuracy is stored as a plain number on the accuracy/2 fact.
% Bands are inclusive/exclusive as written: >95 high, 80–95 moderate, ≤80 low.

high_accuracy(Paper) :-
  accuracy(Paper, A),
  A > 95.

moderate_accuracy(Paper) :-
  accuracy(Paper, A),
  A > 80,
  A =< 95.

low_accuracy(Paper) :-
  accuracy(Paper, A),
  A =< 80.

% ── Comparison inference ──────────────────────────────────────────────────────
% Used by chat.service.ts when a user asks "which paper performed better?"
% across two notes that both resolved an accuracy fact.

outperforms(P1, P2) :-
  accuracy(P1, A1),
  accuracy(P2, A2),
  A1 > A2.

same_domain(P1, P2) :-
  method(P1, M1),
  method(P2, M2),
  belongs_to(M1, D),
  belongs_to(M2, D),
  P1 \= P2.

same_dataset(P1, P2) :-
  dataset(P1, D),
  dataset(P2, D),
  P1 \= P2.

% ── Recommendation ────────────────────────────────────────────────────────────
% related_to/2 facts come straight from OntologyRelation edges (weight 0.7
% in the graph). This surfaces a "you might also want to read about X" link
% for flashcard.service.ts and chat.service.ts.

recommended_baseline(Paper, Baseline) :-
  method(Paper, Method),
  related_to(Method, Baseline).

% ── Quiz fact generation ──────────────────────────────────────────────────────
% key_fact/3 is the single entry point quiz.service.ts queries via
% queryAll(['key_fact(NoteId, Type, Val)']). Each solution becomes one
% candidate MCQ. Type is always an atom so quiz.service.ts can switch on it
% to pick a question template (method/dataset/accuracy/domain/task).

key_fact(Paper, method, Method) :-
  method(Paper, Method).

key_fact(Paper, dataset, Dataset) :-
  dataset(Paper, Dataset).

key_fact(Paper, accuracy, Acc) :-
  accuracy(Paper, Acc).

key_fact(Paper, domain, Domain) :-
  method(Paper, M),
  belongs_to(M, Domain).

key_fact(Paper, task, Task) :-
  solves(Paper, Task).

% ── Explanation support ───────────────────────────────────────────────────────
% explains_domain/3 gives chat.service.ts a single fact to build the
% human-readable trace from, instead of re-deriving belongs_to/2 manually:
%   "CNN is_a DeepLearning is_a ML → paper belongs to ML domain"
% Only fires for the direct is_a hop, keeping the explanation one level deep;
% the recursive belongs_to/2 above already proved transitivity.

explains_domain(Paper, Method, Domain) :-
  method(Paper, Method),
  is_a(Method, Domain).

% ── Confidence support ────────────────────────────────────────────────────────
% has_direct_evidence/1 distinguishes papers whose domain classification
% rests on a single is_a hop (strong) from ones that needed the recursive
% belongs_to/2 chain (weaker, more inferred). prolog.engine.ts uses this to
% set PrologResult.confidence: 1.0 for direct, 0.7 for chained.

has_direct_evidence(Paper) :-
  method(Paper, Method),
  dataset(Paper, _),
  accuracy(Paper, _),
  solves(Paper, _),
  belongs_to(Method, _).