import type { NextRequest, NextResponse } from "next/server";
import * as adminService from "@/server/services/admin.service";
import { validateBody, validateQuery } from "@/server/middleware/validation.middleware";
import { successResponse, noContentResponse, paginatedResponse } from "@/server/utils/response";
import { BadRequestError } from "@/server/utils/errors";
import { userQuerySchema, updateRoleSchema } from "@/server/validators/admin.validator";
import type { AuthContext } from "@/server/middleware/auth.middleware";

type RouteParams = { params: { id: string } };

// ASSUMPTION: no shared ID validator exists yet (roadmap lists this under
// Week 7 "Input sanitization", still unbuilt). Inlined here — move to
// server/utils/validators.ts once that block lands, and swap this out.
// Note: validates UUID v4 format (not Mongo ObjectId hex) — User._id is a
// UUID string generated by UserEntity.create() via randomUUID(), not an
// auto-generated Mongo ObjectId.
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function requireUserId(id: string | undefined): string {
  if (!id || !UUID_REGEX.test(id)) {
    throw new BadRequestError("Invalid user id");
  }
  return id;
}

// ─── List / read ──────────────────────────────────────────────────────────────

// GET /api/admin/users
export async function listUsers(req: NextRequest, _ctx: AuthContext): Promise<NextResponse> {
  const query = validateQuery(req, userQuerySchema);
  const result = await adminService.listUsers(query);
  return paginatedResponse(
    result.data, 
    result.meta,
    "Users retrieved"
  );
}

// GET /api/admin/users/[id]
export async function getUser(
  _req: NextRequest,
  _ctx: AuthContext,
  { params }: RouteParams
): Promise<NextResponse> {
  const targetId = requireUserId(params.id);
  const user = await adminService.getUserById(targetId);
  return successResponse(user);
}

// GET /api/admin/users/stats
export async function getUserStats(_req: NextRequest, _ctx: AuthContext): Promise<NextResponse> {
  const stats = await adminService.getUserStats();
  return successResponse(stats);
}

// ─── Mutations ────────────────────────────────────────────────────────────────

// PATCH /api/admin/users/[id]/role
export async function updateUserRole(
  req: NextRequest,
  ctx: AuthContext,
  { params }: RouteParams
): Promise<NextResponse> {
  const targetId = requireUserId(params.id);
  const { role } = await validateBody(req, updateRoleSchema);
  await adminService.updateUserRole(ctx.userId, targetId, role);
  return successResponse({ message: "Role updated" });
}

// POST /api/admin/users/[id]/ban
export async function banUser(
  _req: NextRequest,
  ctx: AuthContext,
  { params }: RouteParams
): Promise<NextResponse> {
  const targetId = requireUserId(params.id);
  await adminService.banUser(ctx.userId, targetId);
  return successResponse({ message: "User banned" });
}

// POST /api/admin/users/[id]/unban
export async function unbanUser(
  _req: NextRequest,
  ctx: AuthContext,
  { params }: RouteParams
): Promise<NextResponse> {
  const targetId = requireUserId(params.id);
  await adminService.unbanUser(ctx.userId, targetId);
  return successResponse({ message: "User unbanned" });
}

// DELETE /api/admin/users/[id]
export async function deleteUser(
  _req: NextRequest,
  ctx: AuthContext,
  { params }: RouteParams
): Promise<NextResponse> {
  const targetId = requireUserId(params.id);
  await adminService.deleteUser(ctx.userId, targetId);
  return noContentResponse();
}