"use client";

import {
  useCallback,
  useEffect,
  useState,
} from "react";

import {
  CheckCircle2,
  Clock3,
  RefreshCw,
  Sparkles,
  XCircle,
} from "lucide-react";

import {
  Topbar,
} from "@/components/layout/Topbar";

import {
  getStudentAIUsage,
} from "@/services/ai-usage.service";

import type {
  StudentAIUsage,
} from "@/types/ai-usage";

function formatLatency(
  value: number,
): string {
  if (
    !Number.isFinite(value) ||
    value <= 0
  ) {
    return "—";
  }

  return value >= 1_000
    ? `${(value / 1_000).toFixed(1)}s`
    : `${Math.round(value)}ms`;
}

function formatTime(
  value: string,
): string {
  const date =
    new Date(value);

  return Number.isNaN(
    date.getTime(),
  )
    ? "—"
    : date.toLocaleString();
}

export default function StudentAIUsagePage() {
  const [
    data,
    setData,
  ] =
    useState<StudentAIUsage | null>(
      null,
    );

  const [
    error,
    setError,
  ] =
    useState<string | null>(
      null,
    );

  const [
    refreshing,
    setRefreshing,
  ] =
    useState(false);

  const load =
    useCallback(
      async () => {
        try {
          const result =
            await getStudentAIUsage();

          setData(result);
          setError(null);
        } catch (cause) {
          setError(
            cause instanceof Error
              ? cause.message
              : "AI usage is unavailable.",
          );
        } finally {
          setRefreshing(false);
        }
      },
      [],
    );

  useEffect(() => {
    const timer =
      window.setTimeout(
        () => {
          void load();
        },
        0,
      );

    return () => {
      window.clearTimeout(
        timer,
      );
    };
  }, [load]);

  const refresh =
    useCallback(() => {
      setRefreshing(true);
      void load();
    }, [load]);

  return (
    <>
      <Topbar
        eyebrow="Account"
        title="AI Usage"
      />

      <div className="mb-5 flex items-center justify-between gap-3">
        <p className="text-[12px] text-ink-faint">
          Provider usage generated by your account only.
          Symbolic-only study generation does not consume provider usage.
        </p>

        <button
          type="button"
          disabled={refreshing}
          onClick={refresh}
          className="inline-flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-[12px] text-ink-soft disabled:opacity-50"
        >
          <RefreshCw
            size={14}
            className={
              refreshing
                ? "animate-spin"
                : ""
            }
          />
          Refresh
        </button>
      </div>

      {error && (
        <div className="mb-5 rounded-xl border border-coral/30 bg-coral-soft px-4 py-3 text-[12px] text-coral">
          {error}
        </div>
      )}

      {!data && !error && (
        <div className="rounded-xl border border-line bg-paper-raised px-4 py-10 text-center text-[12px] text-ink-faint">
          Loading AI usage…
        </div>
      )}

      {data && (
        <>
          <section className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-6">
            {[
              [
                "Requests today",
                data.summary.requestsToday.toLocaleString(),
              ],
              [
                "Tokens today",
                data.summary.tokensToday.toLocaleString(),
              ],
              [
                "Success rate",
                `${data.summary.successRate.toFixed(1)}%`,
              ],
              [
                "Successful",
                data.summary.successesToday.toLocaleString(),
              ],
              [
                "Failed",
                data.summary.failuresToday.toLocaleString(),
              ],
              [
                "Avg latency",
                formatLatency(
                  data.summary.averageLatencyMs,
                ),
              ],
            ].map(
              ([label, value]) => (
                <div
                  key={label}
                  className="rounded-xl border border-line bg-paper-raised p-4"
                >
                  <p className="text-[11px] text-ink-faint">
                    {label}
                  </p>

                  <p className="mt-2 font-serif text-2xl font-semibold text-ink">
                    {value}
                  </p>
                </div>
              ),
            )}
          </section>

          <section className="mb-5 grid grid-cols-1 gap-4 lg:grid-cols-2">
            <div className="rounded-xl border border-line bg-paper-raised p-5">
              <h2 className="font-serif text-[16px] font-semibold text-ink">
                Last 7 days
              </h2>

              <div className="mt-4 divide-y divide-line-soft">
                {data.lastSevenDays.map(
                  (day) => (
                    <div
                      key={day.date}
                      className="flex items-center justify-between py-3 text-[12px]"
                    >
                      <div>
                        <p className="text-ink">
                          {day.label}
                        </p>

                        <p className="mt-0.5 text-[10px] text-ink-faint">
                          {day.date}
                        </p>
                      </div>

                      <div className="text-right">
                        <p className="font-mono text-ink">
                          {day.requests} request
                          {day.requests === 1
                            ? ""
                            : "s"}
                        </p>

                        <p className="mt-0.5 font-mono text-[10px] text-ink-faint">
                          {day.tokens.toLocaleString()} tokens
                        </p>
                      </div>
                    </div>
                  ),
                )}
              </div>
            </div>

            <div className="rounded-xl border border-line bg-paper-raised p-5">
              <h2 className="font-serif text-[16px] font-semibold text-ink">
                Provider usage
              </h2>

              <div className="mt-4 space-y-3">
                {data.providers.map(
                  (provider) => (
                    <div
                      key={provider.provider}
                      className="rounded-lg border border-line-soft p-3"
                    >
                      <div className="flex items-center justify-between">
                        <span className="capitalize text-[12px] font-medium text-ink">
                          {provider.provider}
                        </span>

                        <span className="font-mono text-[11px] text-ink-soft">
                          {provider.requests} requests
                        </span>
                      </div>

                      <div className="mt-3 grid grid-cols-3 gap-3 text-[10px]">
                        <div>
                          <p className="text-ink-faint">
                            Tokens
                          </p>
                          <p className="mt-1 font-mono text-ink">
                            {provider.tokens.toLocaleString()}
                          </p>
                        </div>

                        <div>
                          <p className="text-ink-faint">
                            Success
                          </p>
                          <p className="mt-1 font-mono text-ink">
                            {provider.successes}
                          </p>
                        </div>

                        <div>
                          <p className="text-ink-faint">
                            Failed
                          </p>
                          <p className="mt-1 font-mono text-ink">
                            {provider.failures}
                          </p>
                        </div>
                      </div>
                    </div>
                  ),
                )}
              </div>
            </div>
          </section>

          <section className="mb-5 rounded-xl border border-line bg-paper-raised p-5">
            <h2 className="font-serif text-[16px] font-semibold text-ink">
              Usage by feature
            </h2>

            <div className="mt-4 overflow-x-auto">
              <table className="w-full min-w-[620px] text-left text-[12px]">
                <thead className="text-ink-faint">
                  <tr>
                    <th className="px-3 py-2 font-medium">
                      Feature
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Requests
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Success
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Failed
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Tokens
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {data.features.map(
                    (feature) => (
                      <tr
                        key={feature.label}
                        className="border-t border-line-soft"
                      >
                        <td className="px-3 py-3 font-medium text-ink">
                          {feature.label}
                        </td>
                        <td className="px-3 py-3 font-mono text-ink-soft">
                          {feature.requests}
                        </td>
                        <td className="px-3 py-3 font-mono text-ink-soft">
                          {feature.successes}
                        </td>
                        <td className="px-3 py-3 font-mono text-ink-soft">
                          {feature.failures}
                        </td>
                        <td className="px-3 py-3 font-mono text-ink-soft">
                          {feature.tokens.toLocaleString()}
                        </td>
                      </tr>
                    ),
                  )}

                  {data.features.length ===
                    0 && (
                    <tr>
                      <td
                        colSpan={5}
                        className="border-t border-line-soft px-3 py-8 text-center text-ink-faint"
                      >
                        No provider usage recorded for your account yet.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>

          <section className="rounded-xl border border-line bg-paper-raised p-5">
            <div className="mb-4 flex items-center gap-2">
              <Sparkles
                size={16}
                className="text-ink-faint"
              />

              <h2 className="font-serif text-[16px] font-semibold text-ink">
                Recent provider activity
              </h2>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full min-w-[760px] text-left text-[12px]">
                <thead className="text-ink-faint">
                  <tr>
                    <th className="px-3 py-2 font-medium">
                      Result
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Feature
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Provider
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Tokens
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Latency
                    </th>
                    <th className="px-3 py-2 font-medium">
                      Time
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {data.recentActivity.map(
                    (item) => (
                      <tr
                        key={item.id}
                        className="border-t border-line-soft"
                      >
                        <td className="px-3 py-3">
                          {item.success ? (
                            <span className="inline-flex items-center gap-1 text-sage">
                              <CheckCircle2 size={12} />
                              Success
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 text-coral">
                              <XCircle size={12} />
                              Failed
                            </span>
                          )}
                        </td>

                        <td className="px-3 py-3 text-ink">
                          {item.usageLabel}
                        </td>

                        <td className="px-3 py-3">
                          <p className="capitalize text-ink">
                            {item.provider}
                          </p>
                          <p className="mt-0.5 font-mono text-[10px] text-ink-faint">
                            {item.model}
                          </p>
                        </td>

                        <td className="px-3 py-3 font-mono text-ink-soft">
                          {item.tokensUsed.toLocaleString()}
                        </td>

                        <td className="px-3 py-3 font-mono text-ink-soft">
                          <span className="inline-flex items-center gap-1">
                            <Clock3 size={11} />
                            {formatLatency(
                              item.latencyMs,
                            )}
                          </span>
                        </td>

                        <td className="px-3 py-3 whitespace-nowrap text-ink-faint">
                          {formatTime(
                            item.createdAt,
                          )}
                        </td>
                      </tr>
                    ),
                  )}

                  {data.recentActivity.length ===
                    0 && (
                    <tr>
                      <td
                        colSpan={6}
                        className="border-t border-line-soft px-3 py-8 text-center text-ink-faint"
                      >
                        Your account has no durable provider activity yet.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}
    </>
  );
}
